wandb_version: 1

seed:
  desc: null
  value: 1234
checkpoint:
  desc: null
  value: null
data_dir:
  desc: null
  value: /net/cephfs/shares/rpg.ifi.uzh/tsoyda/data/dvslip
output_dir:
  desc: null
  value: ./outputs/2024-09-26-14-20-47
checkpoint_dir:
  desc: null
  value: ./checkpoints
model:
  desc: null
  value:
    ssm_init:
      C_init: lecun_normal
      dt_min: 0.001
      dt_max: 0.1
      conj_sym: false
      clip_eigs: true
      input_dependent: true
      stablessm_a: false
      separate_dbc: false
      log_a: false
      bidirectional: false
    ssm:
      discretization: zoh
      d_model: 36
      d_ssm: 8
      ssm_block_size: 4
      num_stages: 1
      num_layers_per_stage: 1
      dropout: 0.19493287684529745
      classification_mode: pool
      prenorm: true
      batchnorm: true
      bn_momentum: 0.95
      pooling_stride: 1
      pooling_mode: last
      state_expansion_factor: 1
      encoder_type: dense
task:
  desc: null
  value:
    name: eigenworms-classification
training:
  desc: null
  value:
    num_epochs: 1600
    per_device_batch_size: 6
    per_device_eval_batch_size: 20
    num_workers: 16
    cut_mix: 0.0
    pad_unit: 17984
    no_time_information: true
optimizer:
  desc: null
  value:
    ssm_base_lr: 0.0003204789646136706
    lr_factor: 4
    warmup_epochs: 1
    ssm_weight_decay: 0.02275975287136827
    weight_decay: 0.029755403494251292
    schedule: cosine
    accumulation_steps: 1
    proj_weight_decay: 0.03203944987024569
    total_steps: 48000
    warmup_steps: 30
    ssm_lr: 0.0019228737876820236
logging:
  desc: null
  value:
    log_dir: ./outputs/2024-09-26-14-20-47
    interval: 500
    wandb: true
    summary_metric: Performance/Validation accuracy
    project: thesis
    entity: taylansoydan
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727353262
    t:
      1:
      - 1
      - 12
      - 40
      - 41
      - 45
      - 49
      - 50
      - 51
      - 55
      2:
      - 1
      - 12
      - 40
      - 41
      - 45
      - 49
      - 50
      - 51
      - 55
      3:
      - 7
      - 16
      - 23
      - 37
      - 62
      - 63
      4: 3.10.9
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: Performance/Validation accuracy
      6:
      - 3
      7:
      - 2
model.ssm.bn_momentum:
  desc: null
  value: 0.95
model.ssm.classification_mode:
  desc: null
  value: pool
model.ssm.d_model:
  desc: null
  value: 36
model.ssm.d_ssm:
  desc: null
  value: 8
model.ssm.discretization:
  desc: null
  value: zoh
model.ssm.dropout:
  desc: null
  value: 0.19493287684529745
model.ssm.num_layers_per_stage:
  desc: null
  value: 1
model.ssm.num_stages:
  desc: null
  value: 1
model.ssm.pooling_stride:
  desc: null
  value: 1
model.ssm.ssm_block_size:
  desc: null
  value: 4
model.ssm.state_expansion_factor:
  desc: null
  value: 1
model.ssm_init.bidirectional:
  desc: null
  value: false
model.ssm_init.clip_eigs:
  desc: null
  value: true
model.ssm_init.conj_sym:
  desc: null
  value: false
model.ssm_init.dt_max:
  desc: null
  value: 0.1
model.ssm_init.dt_min:
  desc: null
  value: 0.001
model.ssm_init.input_dependent:
  desc: null
  value: true
model.ssm_init.separate_dbc:
  desc: null
  value: false
model.ssm_init.stablessm_a:
  desc: null
  value: false
optimizer.accumulation_steps:
  desc: null
  value: 1
optimizer.lr_factor:
  desc: null
  value: 4
optimizer.proj_weight_decay:
  desc: null
  value: 0.03203944987024569
optimizer.ssm_base_lr:
  desc: null
  value: 0.0003204789646136706
optimizer.ssm_weight_decay:
  desc: null
  value: 0.02275975287136827
optimizer.warmup_epochs:
  desc: null
  value: 1
optimizer.weight_decay:
  desc: null
  value: 0.029755403494251292
training.num_epochs:
  desc: null
  value: 1600
training.per_device_batch_size:
  desc: null
  value: 6
training.per_device_eval_batch_size:
  desc: null
  value: 20
SLURM_JOB_ID:
  desc: null
  value: '16432506'
