# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.0015
    dt_max: 0.1
    conj_sym: true
    clip_eigs: true
    input_dependent: true
    stablessm_a: true
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: async
    d_model: 32
    d_ssm: 32
    ssm_block_size: 8
    num_stages: 2
    num_layers_per_stage: 4
    dropout: 0.2517000716418498
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 8
    pooling_mode: timepool
    state_expansion_factor: 1
    encoder_type: embed
