# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.001
    dt_max: 0.1
    conj_sym: true
    clip_eigs: false #true
    input_dependent: false # New
    stablessm_a: false # New
    separate_dbc: false # New
    log_a: false # New
    bidirectional: true # New
  ssm:
    discretization: zoh
    d_model: 256 # 32 128
    d_ssm: 192 # 32 128
    ssm_block_size: 16
    num_stages: 1 #3 # 1 2
    num_layers_per_stage: 6 #2 #3
    dropout: 0.1 #0.25
    classification_mode: pool
    prenorm: true #true
    batchnorm: true #true
    bn_momentum: 0.95
    pooling_stride: 1 #8 #16 # 1 16
    pooling_mode: avgpool #avgpool #last
    state_expansion_factor: 1 # 1 2
    encoder_type: embed
    
