# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 1.1019624854621432e-05
    dt_max: 0.1
    conj_sym: false
    clip_eigs: true
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: zoh
    d_model: 70
    d_ssm: 8
    ssm_block_size: 2
    num_stages: 1
    num_layers_per_stage: 3
    dropout: 0.13437002775451784
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: avgpool
    state_expansion_factor: 1
    encoder_type: embed
