seed: 1234
checkpoint: null
data_dir: /net/cephfs/shares/rpg.ifi.uzh/tsoyda/data/dvslip
output_dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
checkpoint_dir: ./checkpoints
model:
  ssm_init:
    C_init: trunc_standard_normal
    dt_min: 5.0e-05
    dt_max: 0.1
    conj_sym: true
    clip_eigs: false
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: zoh
    d_model: 50
    d_ssm: 2
    ssm_block_size: 2
    num_stages: 1
    num_layers_per_stage: 6
    dropout: 0.006383445496769972
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: last
    state_expansion_factor: 1
    encoder_type: embed
task:
  name: pathfinder-classification
training:
  num_epochs: 200
  per_device_batch_size: 16
  per_device_eval_batch_size: 28
  num_workers: 40
  cut_mix: 0.0
  pad_unit: 1024
  no_time_information: true
optimizer:
  ssm_base_lr: 2.9595708602151775e-05
  lr_factor: 4
  warmup_epochs: 1
  ssm_weight_decay: 0.010869283679557832
  weight_decay: 0.010127085396168325
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.01427424100456811
logging:
  log_dir: ${output_dir}
  interval: 1000
  wandb: true
  summary_metric: Performance/Validation accuracy
  project: thesis
  entity: taylansoydan
