# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.004
    dt_max: 0.1
    conj_sym: true #false
    clip_eigs: false #false
    input_dependent: true # New
    stablessm_a: true # New
    separate_dbc: false # New
    log_a: false # New
    bidirectional: false #true # New
  ssm:
    discretization: async
    d_model: 64
    d_ssm: 8
    ssm_block_size: 8 #8
    num_stages: 1 #2
    num_layers_per_stage: 6
    dropout: 0.1
    classification_mode: pool
    prenorm: true
    batchnorm: false
    bn_momentum: 0.95
    pooling_stride: 8 #8
    pooling_mode: avgpool
    state_expansion_factor: 1
    encoder_type: embed
