# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 3.3528788827593204e-07
    dt_max: 0.1
    conj_sym: false
    clip_eigs: true
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: true
  ssm:
    discretization: async
    d_model: 44
    d_ssm: 48
    ssm_block_size: 4
    num_stages: 1
    num_layers_per_stage: 1
    dropout: 0.6241915931552915
    classification_mode: none
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: last
    state_expansion_factor: 1
    encoder_type: embed
