# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 7.066894232821676e-09
    dt_max: 0.1
    conj_sym: false
    clip_eigs: true
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: zoh
    d_model: 30
    d_ssm: 48
    ssm_block_size: 4
    num_stages: 1
    num_layers_per_stage: 4
    dropout: 0.11497226575398677
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: last
    state_expansion_factor: 1
