wandb_version: 1

seed:
  desc: null
  value: 1234
checkpoint:
  desc: null
  value: null
data_dir:
  desc: null
  value: /net/cephfs/shares/rpg.ifi.uzh/tsoyda/data/dvslip
output_dir:
  desc: null
  value: ./outputs/2024-11-20-11-58-09
checkpoint_dir:
  desc: null
  value: ./checkpoints
model:
  desc: null
  value:
    ssm_init:
      C_init: lecun_normal
      dt_min: 7.066894232821676e-09
      dt_max: 0.1
      conj_sym: false
      clip_eigs: true
      input_dependent: true
      stablessm_a: false
      separate_dbc: false
      log_a: false
      bidirectional: false
    ssm:
      discretization: zoh
      d_model: 30
      d_ssm: 48
      ssm_block_size: 4
      num_stages: 1
      num_layers_per_stage: 4
      dropout: 0.11497226575398677
      classification_mode: pool
      prenorm: true
      batchnorm: true
      bn_momentum: 0.95
      pooling_stride: 1
      pooling_mode: last
      state_expansion_factor: 1
task:
  desc: null
  value:
    name: image-classification
training:
  desc: null
  value:
    num_epochs: 200
    per_device_batch_size: 20
    per_device_eval_batch_size: 70
    num_workers: 40
    cut_mix: 0.0
    pad_unit: 1024
    no_time_information: true
optimizer:
  desc: null
  value:
    ssm_base_lr: 7.057556033116367e-06
    lr_factor: 16
    warmup_epochs: 5
    ssm_weight_decay: 0.023777584092325364
    weight_decay: 0.07157995928590169
    schedule: cosine
    accumulation_steps: 1
    proj_weight_decay: 0.016497069921660678
    total_steps: 450000
    warmup_steps: 11250
    ssm_lr: 0.00014115112066232736
logging:
  desc: null
  value:
    log_dir: ./outputs/2024-11-20-11-58-09
    interval: 1000
    wandb: true
    summary_metric: Performance/Validation accuracy
    project: thesis
    entity: taylansoydan
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732100318
    t:
      1:
      - 1
      - 12
      - 40
      - 41
      - 45
      - 49
      - 50
      - 51
      - 55
      2:
      - 1
      - 12
      - 40
      - 41
      - 45
      - 49
      - 50
      - 51
      - 55
      3:
      - 7
      - 16
      - 23
      - 37
      - 62
      - 63
      4: 3.10.9
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: Performance/Validation accuracy
      6:
      - 3
      7:
      - 2
model.ssm.bn_momentum:
  desc: null
  value: 0.95
model.ssm.d_model:
  desc: null
  value: 30
model.ssm.d_ssm:
  desc: null
  value: 48
model.ssm.dropout:
  desc: null
  value: 0.11497226575398677
model.ssm.num_layers_per_stage:
  desc: null
  value: 4
model.ssm.num_stages:
  desc: null
  value: 1
model.ssm.pooling_stride:
  desc: null
  value: 1
model.ssm.ssm_block_size:
  desc: null
  value: 4
model.ssm.state_expansion_factor:
  desc: null
  value: 1
model.ssm_init.bidirectional:
  desc: null
  value: false
model.ssm_init.clip_eigs:
  desc: null
  value: true
model.ssm_init.conj_sym:
  desc: null
  value: false
model.ssm_init.dt_min:
  desc: null
  value: 7.066894232821676e-09
model.ssm_init.stablessm_a:
  desc: null
  value: false
optimizer.accumulation_steps:
  desc: null
  value: 1
optimizer.lr_factor:
  desc: null
  value: 16
optimizer.proj_weight_decay:
  desc: null
  value: 0.016497069921660678
optimizer.ssm_base_lr:
  desc: null
  value: 7.057556033116367e-06
optimizer.ssm_weight_decay:
  desc: null
  value: 0.023777584092325364
optimizer.warmup_epochs:
  desc: null
  value: 5
optimizer.weight_decay:
  desc: null
  value: 0.07157995928590169
training.num_epochs:
  desc: null
  value: 200
training.per_device_batch_size:
  desc: null
  value: 20
training.per_device_eval_batch_size:
  desc: null
  value: 70
SLURM_JOB_ID:
  desc: null
  value: '18290841'
