seed: 1234
checkpoint: null
data_dir: /net/cephfs/shares/rpg.ifi.uzh/tsoyda/data/dvslip
output_dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
checkpoint_dir: ./checkpoints
model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 7.066894232821676e-09
    dt_max: 0.1
    conj_sym: false
    clip_eigs: true
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: zoh
    d_model: 30
    d_ssm: 48
    ssm_block_size: 4
    num_stages: 1
    num_layers_per_stage: 4
    dropout: 0.11497226575398677
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: last
    state_expansion_factor: 1
task:
  name: image-classification
training:
  num_epochs: 200
  per_device_batch_size: 20
  per_device_eval_batch_size: 70
  num_workers: 40
  cut_mix: 0.0
  pad_unit: 1024
  no_time_information: true
optimizer:
  ssm_base_lr: 7.057556033116367e-06
  lr_factor: 16
  warmup_epochs: 5
  ssm_weight_decay: 0.023777584092325364
  weight_decay: 0.07157995928590169
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.016497069921660678
logging:
  log_dir: ${output_dir}
  interval: 1000
  wandb: true
  summary_metric: Performance/Validation accuracy
  project: thesis
  entity: taylansoydan
