# @package _global_
defaults:
  - /model: ptb/small

task:
  name: ptb-classification

training:
  num_epochs: 50 #200
  per_device_batch_size: 128 #128 #64
  per_device_eval_batch_size: 128 #128 #64
  num_workers: 96
  cut_mix: 0.0
  pad_unit: 100
  no_time_information: true
  loss_type: one_hot_cross_entropy
  
optimizer:
  ssm_base_lr: 0.0001
  lr_factor: 3
  warmup_epochs: 1
  ssm_weight_decay: 0
  weight_decay: 0.5
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.0