# @package _global_

defaults:
  - /model: retrieval/small

task:
  name: retrieval-classification

training:
  num_epochs: 2
  per_device_batch_size: 60
  per_device_eval_batch_size: 60
  num_workers: 48
  cut_mix: 0.0
  pad_unit: 4000
  no_time_information: true
  loss_type: cross_entropy

optimizer:
  ssm_base_lr: 0.0001
  lr_factor: 3
  warmup_epochs: 1
  ssm_weight_decay: 0.07
  weight_decay: 0.05
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.04