# @package _global_
#defaults:
#  - /model: shd/medium
model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.004
    dt_max: 0.1
    conj_sym: false
    clip_eigs: false #false
    input_dependent: true # New
    stablessm_a: true # New
    separate_dbc: false # New
    log_a: false # New
  ssm:
    discretization: async
    d_model: 8 #96
    d_ssm: 16 #128
    ssm_block_size: 8
    num_stages: 2 #2
    num_layers_per_stage: 3 #
    dropout: 0.23
    classification_mode: pool
    prenorm: true
    batchnorm: false
    bn_momentum: 0.95
    pooling_stride: 8 #8
    pooling_mode: avgpool
    state_expansion_factor: 1


task:
  name: shd-classification

training:
  num_epochs: 30
  per_device_batch_size: 32 #32
  per_device_eval_batch_size: 64 #128
  num_workers: 32
  time_jitter: 1
  spatial_jitter: 0.55
  noise: 35
  max_drop_chunk: 0.02
  drop_event: 0.1
  time_skew: 1.2
  cut_mix: 0.3
  pad_unit: 8192
  validate_on_test: true

optimizer:
  ssm_base_lr: 1.7e-5
  lr_factor: 10
  warmup_epochs: 3
  ssm_weight_decay: 0.0
  weight_decay: 0.03
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.001