# @package _global_
defaults:
  - /model: text/small

task:
  name: text-classification

training:
  num_epochs: 200
  per_device_batch_size: 1 #50
  per_device_eval_batch_size: 1 #50
  num_workers: 40
  cut_mix: 0.0
  pad_unit: 4100 #4096 #32768 #524288
  no_time_information: true
  loss_type: cross_entropy

optimizer:
  ssm_base_lr: 0.001
  lr_factor: 4
  warmup_epochs: 1
  ssm_weight_decay: 0.0
  weight_decay: 0.07
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.0