seed: 1234
checkpoint: null
data_dir: /net/cephfs/shares/rpg.ifi.uzh/tsoyda/data/dvslip
output_dir: ./outputs/${now:%Y-%m-%d-%H-%M-%S}
checkpoint_dir: ./checkpoints
model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.001
    dt_max: 0.1
    conj_sym: false
    clip_eigs: true
    input_dependent: true
    stablessm_a: false
    separate_dbc: false
    log_a: false
    bidirectional: false
  ssm:
    discretization: zoh
    d_model: 36
    d_ssm: 8
    ssm_block_size: 4
    num_stages: 1
    num_layers_per_stage: 1
    dropout: 0.19493287684529745
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: last
    state_expansion_factor: 1
    encoder_type: dense
task:
  name: eigenworms-classification
training:
  num_epochs: 1600
  per_device_batch_size: 6
  per_device_eval_batch_size: 20
  num_workers: 16
  cut_mix: 0.0
  pad_unit: 17984
  no_time_information: true
optimizer:
  ssm_base_lr: 0.0003204789646136706
  lr_factor: 4
  warmup_epochs: 1
  ssm_weight_decay: 0.02275975287136827
  weight_decay: 0.029755403494251292
  schedule: cosine
  accumulation_steps: 1
  proj_weight_decay: 0.03203944987024569
logging:
  log_dir: ${output_dir}
  interval: 500
  wandb: true
  summary_metric: Performance/Validation accuracy
  project: thesis
  entity: taylansoydan
