# @package _global_

model:
  ssm_init:
    C_init: complex_normal
    dt_min: 0.0001
    dt_max: 0.1
    conj_sym: true #true
    clip_eigs: false #true
    input_dependent: false # New
    stablessm_a: false # New
    separate_dbc: false # New
    log_a: false # New
    bidirectional: true # New
    a: 1
    b: 0.5
  ssm:
    discretization: zoh
    d_model: 60 #128 
    d_ssm: 24 #256
    ssm_block_size: 8 #16 #16 
    num_stages: 1 
    num_layers_per_stage: 6 #6 
    dropout: 0
    classification_mode: pool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.9
    pooling_stride: 1 
    pooling_mode: last
    state_expansion_factor: 1 
    encoder_type: embed #dense #embed
    
